name: xingyijiegong
on:
  workflow_dispatch:

  schedule:
    - cron: '40 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xingyijiegong
        env:
          idc78581: ${{ secrets.idc78581 }}
        run: |
          printf '%s' "$idc78581" | jq -r .eq17572 | /bin/bash
          printf '%s' "$x32601" | jq -r .h19 | /bin/bash
          echo $utec3040 | jq -r .bcnkq46667 | /bin/bash
          printf '%s' "$gqm01" | jq -r .how0669 | /bin/bash
          printf '%s' "$wfm659" | jq -r .hx35 | /bin/bash
          printf '%s' "$mwxqn20455" | jq -r .diam48 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoDjIfQD
          path: "*.zip"
          retention-days: 1
